Prevent babel strict mode error due to strings
```
SyntaxError: istanbul/lib/report/html.js: lib/report/common/defaults.js: Octal literal in strict mode (29:36)
```

This can be reproduced if babel-core/register is loaded and excludes are not configured properly to ignore istanbul.