Fix Error while generating HTML report, issue #40
When istanbul module is commited in a SVN repository, generating a HTML report produce the error :

Fatal error: EISDIR, illegal operation on a directory

This is due to the presence of the .svn directory